### ISSUE TITLE
How to get the java bindings?

### ISSUE THREAD

**Issue by donpironet** [GerardSoleCa/Robosodium#4]
I've done everthing like in the readme. I end up with the .so files. Good. Added them to my android studio project loaded the library like this:

```
static {
    System.loadLibrary("kaliumjni");
}
```

What I don't find is the java binding files so that I can use the library. How can I get them? 

Some screenshots of my project structure and my mainactivity where I try to call a function:

![screen shot 2015-11-06 at 13 44 22](https://cloud.githubusercontent.com/assets/6583650/10997333/9347a2d0-848c-11e5-9b46-6efe89220a05.png)
![screen shot 2015-11-06 at 13 44 31](https://cloud.githubusercontent.com/assets/6583650/10997334/935bfe24-848c-11e5-8d37-8f1b7bf38058.png)

**Comment by hbmartin** [comment]
@donpironet what was the resolution?

**Comment by donpironet** [comment]
I just needed to copy paste the JNI bindings from the repo to my project and it worked. Because I'm using another package then your JNI bindings. I just forgot about that.
