### ISSUE TITLE
Publishing to Maven

### ISSUE THREAD

**Issue by benhylau** [GerardSoleCa/Robosodium#5]
Would be great if this can be published to Maven Central, so Gradle builds can pull in a specific version as dependency with just one line. If you are open to that I can make a PR, or I can publish from [my fork](https://github.com/groundupworks/Robosodium). Lmk your thoughts? Thanks.

**Comment by GerardSoleCa** [comment]
Hi! I'm open to that, if you can do a PR I would really appreciate. If not, I'll try to publish it once I've time.

Thanks!

**Comment by benhylau** [comment]
I will do a PR early-Jan, since I am already halfway
https://github.com/groundupworks/Robosodium/tree/mac-compile

What should I use for group and artifact ID? `com.github.gerardsoleca:robosodium`?

**Comment by benhylau** [comment]
Nvm I have some time this morning. The rest is up to you now #6 ;)

**Comment by benhylau** [comment]
Thanks @GerardSoleCa. Let me know when the artifacts are available on a public repo, or if you need any help to have that sorted out.

**Comment by GerardSoleCa** [comment]
Hi!

Yesterday I successfully released a version. I couldn't test it, it was really late. Today I'll try to test it. If you want, you can fetch it from the following artifact:

```
<dependency>
  <groupId>com.github.gerardsoleca</groupId>
  <artifactId>robosodium</artifactId>
  <version>1.0.0</version>
  <type>aar</type>
</dependency>
```

**Comment by benhylau** [comment]
Thanks! I see it on Maven -> http://search.maven.org/#artifactdetails%7Ccom.github.gerardsoleca%7Crobosodium%7C1.0.0%7Caar

Don't forget to release tag :)
Will be using it in my project soon!

**Comment by GerardSoleCa** [comment]
Done :)

https://github.com/GerardSoleCa/Robosodium/releases/tag/v1.0.0

Thanks for all, hope your project succeeds!
