### ISSUE TITLE
minSdkVersion can be lower

### ISSUE THREAD

**Issue by benhylau** [GerardSoleCa/Robosodium#9]
This can actually be a API level 9:
https://github.com/GerardSoleCa/Robosodium/blob/master/build.gradle#L26

**Comment by GerardSoleCa** [comment]
Thanks, lowering the minSdkVersion.

**Comment by GerardSoleCa** [comment]
A new maven release will be done, if possible, next week due to location reasons.

**Comment by benhylau** [comment]
It's not urgent for me to have the new release since it can be overridden by the app Manifest. So whenever you do a new release is fine. Thanks!
